apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: yaheathakeb/expensy-backend:latest
          ports:
            - containerPort: 4000
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017
            - name: REDIS_URL
              value: redis://redis:6379

