name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend
        run: |
          docker build -t yaheathakeb/expensy-backend:latest ./expensy_backend
          docker push yaheathakeb/expensy-backend:latest

      - name: Build and push frontend
        run: |
          docker build -t yaheathakeb/expensy-frontend:latest ./expensy_frontend
          docker push yaheathakeb/expensy-frontend:latest

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Get AKS credentials
        run: |
          az aks get-credentials --resource-group Y_Thakeb-rg --name Y_Thakeb-cluster

      - name: Deploy to AKS
        run: |
          kubectl apply -f k8s/

